name: mason_coder
description: >
  Simple code to template conveter for Mason Brick.
  Solves the problem with development of large Mason Bricks. 
  Now you can use your testable and runnable code for development.
version: 0.1.0+alpha.0
homepage: https://github.com/zoocityboy/mason_coder
repository: https://github.com/zoocityboy/mason_coder
issue_tracker: https://github.com/zoocityboy/mason_coder/issues
documentation: https://zoocityboy.github.io/mason_coder/
topics: [mason, coder, template, generator]
funding: [https://github.com/sponsors/zoocityboy]

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=3.6.0"

# Add regular dependencies here.
dependencies:
  json_annotation: ^4.9.0
  meta: ^1.15.0
  universal_io: ^2.2.2
  promptly:
  path: ^1.9.0
  checked_yaml: ^2.0.3
  yaml: ^3.1.3
  mason: ^0.1.0
  json2yaml: ^3.0.1
  archive: ^3.6.1
  http: ^1.2.2
  tint: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.9.2
  lints: ^5.0.0
  test: ^1.25.14
dependency_overrides:
  promptly:
    path: /Users/zoocityboy/Develop/zoocityboy/promptly
executables: 
  mason_coder:
  mc: mason_coder.dart
