name: eit_feature
description: EmbedIt Platform  Project created by EmbedIt CLI.
version: 1.0.0+2
publish_to: none

environment:
  sdk: ">=3.6.0"
  flutter: ">=3.22.0 <4.0.0"

dependencies:
  eit_core:
    hosted: https://gitea.xops.cz/api/packages/platform/pub/
    version: 0.5.0+1
  eit_injection:
    hosted: https://gitea.xops.cz/api/packages/platform/pub/
    version: 1.8.0
  eit_networking:
    hosted: https://gitea.xops.cz/api/packages/platform/pub/
    version: 3.7.2
  eit_result:
    hosted: https://gitea.xops.cz/api/packages/platform/pub/
    version: 1.3.0
  eit_storage:
    hosted: https://gitea.xops.cz/api/packages/platform/pub/
    version: 1.3.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^8.0.1
  go_router: ^14.3.0

  json_annotation: ^4.9.0
  mason: ^0.1.0-dev.60
  meta: ^1.15.0
  uikit:
    hosted: https://gitea.xops.cz/api/packages/platform/pub/
    version: ^1.0.4

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  eit_lints:
    hosted: https://gitea.xops.cz/api/packages/platform/pub/
    version: ^1.3.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mason_coder:
    path: ../..
  mocktail: ^1.0.4
dependency_overrides:
  intl: 0.19.0
  material_color_utilities: 0.11.1
flutter:
  uses-material-design: true
